cucumber.plugin=pretty,html:target/cucumber-reports/report.html,junit:target/surefire-reports/cucumber-results.xml
cucumber.features=classpath:features
cucumber.glue=com.example.library.cucumber
#cucumber.plugin=pretty, html:target/cucumber-reports/report.html
#cucumber.features=classpath:features
#cucumber.glue=com.example.library.cucumber
